In [16]:
import pandas as pd
file_path = 'retail_sales_dataset.csv'
sales_data = pd.read_csv(file_path)
sales_data.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [23]:
null_v = sales_data.isnull().sum()
sales_data_cleaned = sales_data.dropna()
null_v_after_cleaning = sales_data_cleaned.isnull().sum()
null_v, null_v_after_cleaning

(Transaction ID      0
 Date                0
 Customer ID         0
 Gender              0
 Age                 0
 Product Category    0
 Quantity            0
 Price per Unit      0
 Total Amount        0
 dtype: int64,
 Transaction ID      0
 Date                0
 Customer ID         0
 Gender              0
 Age                 0
 Product Category    0
 Quantity            0
 Price per Unit      0
 Total Amount        0
 dtype: int64)

In [3]:
# General Sales Overview
total_sales_amount = sales_data['Total Amount'].sum()
number_of_transactions = sales_data['Transaction ID'].nunique()
average_transaction_amount = sales_data['Total Amount'].mean()

total_sales_amount, number_of_transactions, average_transaction_amount

(456000, 1000, 456.0)

In [32]:
# Sales by Product Category
sales_by_category = sales_data.groupby('Product Category')['Total Amount'].agg(['sum', 'mean']).reset_index()
sales_by_category.columns = ['Product Category', 'Total Sales', 'Average Sales']
sales_by_category

  Product Category  Total Sales  Average Sales
0           Beauty       143515     467.475570
1         Clothing       155580     443.247863
2      Electronics       156905     458.786550

In [28]:
# Sales distribution by gender
sales_by_gender = sales_data.groupby('Gender')['Total Amount'].agg(['sum', 'mean']).reset_index()
sales_by_gender.columns = ['Gender', 'Total Sales', 'Average Sales']

# Sales distribution by age groups
age_bins = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100]
age_labels = ['0-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-89', '90-100']
sales_data['Age Group'] = pd.cut(sales_data['Age'], bins=age_bins, labels=age_labels, right=False)

sales_by_age_group = sales_data.groupby('Age Group')['Total Amount'].agg(['sum', 'mean']).reset_index()
sales_by_age_group.columns = ['Age Group', 'Total Sales', 'Average Sales']

sales_by_gender, sales_by_age_group

(   Gender  Total Sales  Average Sales
 0  Female       232840     456.549020
 1    Male       223160     455.428571,
   Age Group  Total Sales  Average Sales
 0      0-19        26085     621.071429
 1     20-29        97070     464.449761
 2     30-39        96325     504.319372
 3     40-49        93365     420.563063
 4     50-59        98340     444.977376
 5     60-69        44815     389.695652
 6     70-79            0            NaN
 7     80-89            0            NaN
 8    90-100            0            NaN)

In [27]:
# Convert the 'Date' column to datetime format for analysis
sales_data['Date'] = pd.to_datetime(sales_data['Date'])

# Sales Over Time
sales_data['Month'] = sales_data['Date'].dt.to_period('M')
monthly_sales = sales_data.groupby('Month')['Total Amount'].sum()

# Customer Demographics
gender_sales = sales_data.groupby('Gender')['Total Amount'].sum()
age_groups = pd.cut(sales_data['Age'], bins=[0, 18, 30, 45, 60, 100], labels=['<18', '18-30', '30-45', '45-60', '>60'])
age_sales = sales_data.groupby(age_groups)['Total Amount'].sum()

# Product Category Analysis
category_sales = sales_data.groupby('Product Category')['Total Amount'].sum()

# Sales Performance
quantity_sold = sales_data['Quantity'].sum()
total_revenue = sales_data['Total Amount'].sum()
average_transaction_value = sales_data['Total Amount'].mean()

# Top Customers
top_customers = sales_data.groupby('Customer ID')['Total Amount'].sum().sort_values(ascending=False).head(10)

monthly_sales,gender_sales, age_sales, category_sales, quantity_sold, total_revenue, average_transaction_value, top_customers

(Month
 2023-01    35450
 2023-02    44060
 2023-03    28990
 2023-04    33870
 2023-05    53150
 2023-06    36715
 2023-07    35465
 2023-08    36960
 2023-09    23620
 2023-10    46580
 2023-11    34920
 2023-12    44690
 2024-01     1530
 Freq: M, Name: Total Amount, dtype: int64,
 Gender
 Female    232840
 Male      223160
 Name: Total Amount, dtype: int64,
 Age
 <18       11215
 18-30    121730
 30-45    141955
 45-60    147875
 >60       33225
 Name: Total Amount, dtype: int64,
 Product Category
 Beauty         143515
 Clothing       155580
 Electronics    156905
 Name: Total Amount, dtype: int64,
 2514,
 456000,
 456.0,
 Customer ID
 CUST487    2000
 CUST476    2000
 CUST773    2000
 CUST503    2000
 CUST093    2000
 CUST089    2000
 CUST946    2000
 CUST157    2000
 CUST155    2000
 CUST420    2000
 Name: Total Amount, dtype: int64)